# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraCapivara.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(956, 573)
        Main.setMinimumSize(QtCore.QSize(956, 573))
        Main.setMaximumSize(QtCore.QSize(956, 573))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.Tabs = QtWidgets.QTabWidget(Main)
        self.Tabs.setGeometry(QtCore.QRect(20, 20, 901, 521))
        self.Tabs.setObjectName("Tabs")
        self.tabSomatoria = QtWidgets.QWidget()
        self.tabSomatoria.setObjectName("tabSomatoria")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 251, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbSomatoria1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria1.setText("")
        self.rbSomatoria1.setObjectName("rbSomatoria1")
        self.horizontalLayout.addWidget(self.rbSomatoria1)
        self.lbImgSomatoria1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria1.setText("")
        self.lbImgSomatoria1.setPixmap(QtGui.QPixmap("Images/Somatoria1.PNG"))
        self.lbImgSomatoria1.setObjectName("lbImgSomatoria1")
        self.horizontalLayout.addWidget(self.lbImgSomatoria1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbSomatoria2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria2.setText("")
        self.rbSomatoria2.setObjectName("rbSomatoria2")
        self.horizontalLayout_2.addWidget(self.rbSomatoria2)
        self.lbImgSomatoria2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria2.setText("")
        self.lbImgSomatoria2.setPixmap(QtGui.QPixmap("Images/Somatoria2.PNG"))
        self.lbImgSomatoria2.setObjectName("lbImgSomatoria2")
        self.horizontalLayout_2.addWidget(self.lbImgSomatoria2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rbSomatoria3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria3.setText("")
        self.rbSomatoria3.setObjectName("rbSomatoria3")
        self.horizontalLayout_3.addWidget(self.rbSomatoria3)
        self.lbImgSomatoria3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria3.setText("")
        self.lbImgSomatoria3.setPixmap(QtGui.QPixmap("Images/Somatoria3.PNG"))
        self.lbImgSomatoria3.setObjectName("lbImgSomatoria3")
        self.horizontalLayout_3.addWidget(self.lbImgSomatoria3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 70, 195, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.EntradaK = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.EntradaK.setMinimum(1)
        self.EntradaK.setMaximum(9999999)
        self.EntradaK.setObjectName("EntradaK")
        self.verticalLayout_2.addWidget(self.EntradaK)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.EntradaN = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.EntradaN.setMaximum(9999999)
        self.EntradaN.setObjectName("EntradaN")
        self.verticalLayout_2.addWidget(self.EntradaN)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.EntradaA = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.EntradaA.setMinimum(-99999999.0)
        self.EntradaA.setMaximum(99999999.99)
        self.EntradaA.setObjectName("EntradaA")
        self.verticalLayout_2.addWidget(self.EntradaA)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.EntradaM = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.EntradaM.setEnabled(False)
        self.EntradaM.setMinimum(-99999999.0)
        self.EntradaM.setMaximum(99999999.99)
        self.EntradaM.setObjectName("EntradaM")
        self.verticalLayout_2.addWidget(self.EntradaM)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(520, 110, 361, 251))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.SomatoriaResultado = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.SomatoriaResultado.setPlaceholderText("")
        self.SomatoriaResultado.setObjectName("SomatoriaResultado")
        self.verticalLayout_3.addWidget(self.SomatoriaResultado)
        self.CalcularSomatoria = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CalcularSomatoria.setFont(font)
        self.CalcularSomatoria.setCheckable(False)
        self.CalcularSomatoria.setObjectName("CalcularSomatoria")
        self.verticalLayout_3.addWidget(self.CalcularSomatoria)
        self.Tabs.addTab(self.tabSomatoria, "")
        self.tabConstante = QtWidgets.QWidget()
        self.tabConstante.setObjectName("tabConstante")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabConstante)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 50, 251, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.EntradaPI = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.EntradaPI.setObjectName("EntradaPI")
        self.verticalLayout_4.addWidget(self.EntradaPI)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tabConstante)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(70, 160, 258, 229))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.ResultadoPI = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.ResultadoPI.sizePolicy().hasHeightForWidth())
        self.ResultadoPI.setSizePolicy(sizePolicy)
        self.ResultadoPI.setObjectName("ResultadoPI")
        self.verticalLayout_5.addWidget(self.ResultadoPI)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tabConstante)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 50, 361, 81))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.EntradaEuler = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.EntradaEuler.setObjectName("EntradaEuler")
        self.verticalLayout_6.addWidget(self.EntradaEuler)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tabConstante)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(440, 150, 281, 231))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.ResultadoEuler = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        self.ResultadoEuler.setObjectName("ResultadoEuler")
        self.verticalLayout_7.addWidget(self.ResultadoEuler)
        self.Tabs.addTab(self.tabConstante, "")
        self.tabLogica = QtWidgets.QWidget()
        self.tabLogica.setObjectName("tabLogica")
        self.groupBox = QtWidgets.QGroupBox(self.tabLogica)
        self.groupBox.setGeometry(QtCore.QRect(40, 60, 181, 351))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 160, 321))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.RBnegacao = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBnegacao.setFont(font)
        self.RBnegacao.setChecked(True)
        self.RBnegacao.setObjectName("RBnegacao")
        self.verticalLayout_8.addWidget(self.RBnegacao)
        self.RBconjuncao = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBconjuncao.setFont(font)
        self.RBconjuncao.setObjectName("RBconjuncao")
        self.verticalLayout_8.addWidget(self.RBconjuncao)
        self.RBdisjuncao = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBdisjuncao.setFont(font)
        self.RBdisjuncao.setObjectName("RBdisjuncao")
        self.verticalLayout_8.addWidget(self.RBdisjuncao)
        self.RBcondicional = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.RBcondicional.setFont(font)
        self.RBcondicional.setObjectName("RBcondicional")
        self.verticalLayout_8.addWidget(self.RBcondicional)
        self.RBequivalencia = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBequivalencia.setFont(font)
        self.RBequivalencia.setObjectName("RBequivalencia")
        self.verticalLayout_8.addWidget(self.RBequivalencia)
        self.RBdisjuncaoEX = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBdisjuncaoEX.setFont(font)
        self.RBdisjuncaoEX.setObjectName("RBdisjuncaoEX")
        self.verticalLayout_8.addWidget(self.RBdisjuncaoEX)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabLogica)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 70, 451, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 20, 371, 111))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.RBTrueP = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBTrueP.setFont(font)
        self.RBTrueP.setChecked(True)
        self.RBTrueP.setObjectName("RBTrueP")
        self.verticalLayout_9.addWidget(self.RBTrueP)
        self.RBFalseP = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBFalseP.setFont(font)
        self.RBFalseP.setObjectName("RBFalseP")
        self.verticalLayout_9.addWidget(self.RBFalseP)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.RBTrueQ = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBTrueQ.setFont(font)
        self.RBTrueQ.setObjectName("RBTrueQ")
        self.verticalLayout_10.addWidget(self.RBTrueQ)
        self.RBFalseQ = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBFalseQ.setFont(font)
        self.RBFalseQ.setObjectName("RBFalseQ")
        self.verticalLayout_10.addWidget(self.RBFalseQ)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabLogica)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 240, 461, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 441, 141))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ResultadoLogica = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResultadoLogica.setFont(font)
        self.ResultadoLogica.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultadoLogica.setObjectName("ResultadoLogica")
        self.verticalLayout_11.addWidget(self.ResultadoLogica)
        self.Tabs.addTab(self.tabLogica, "")
        self.tabMatriz = QtWidgets.QWidget()
        self.tabMatriz.setObjectName("tabMatriz")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tabMatriz)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 40, 211, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_16)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(10, 30, 181, 171))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.RBSomaMatriz = QtWidgets.QRadioButton(self.verticalLayoutWidget_20)
        self.RBSomaMatriz.setObjectName("RBSomaMatriz")
        self.verticalLayout_20.addWidget(self.RBSomaMatriz)
        self.RBSubMatriz = QtWidgets.QRadioButton(self.verticalLayoutWidget_20)
        self.RBSubMatriz.setObjectName("RBSubMatriz")
        self.verticalLayout_20.addWidget(self.RBSubMatriz)
        self.RBProdMatriz = QtWidgets.QRadioButton(self.verticalLayoutWidget_20)
        self.RBProdMatriz.setObjectName("RBProdMatriz")
        self.verticalLayout_20.addWidget(self.RBProdMatriz)
        self.RBDetermMatriz = QtWidgets.QRadioButton(self.verticalLayoutWidget_20)
        self.RBDetermMatriz.setObjectName("RBDetermMatriz")
        self.verticalLayout_20.addWidget(self.RBDetermMatriz)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tabMatriz)
        self.groupBox_17.setGeometry(QtCore.QRect(250, 40, 381, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_17)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_5.addWidget(self.label_20)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.spinBox_2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_5.addWidget(self.spinBox_2)
        self.CalculaMatriz = QtWidgets.QPushButton(self.groupBox_17)
        self.CalculaMatriz.setGeometry(QtCore.QRect(120, 140, 121, 41))
        self.CalculaMatriz.setObjectName("CalculaMatriz")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tabMatriz)
        self.groupBox_18.setGeometry(QtCore.QRect(30, 260, 601, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_18)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 581, 171))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Tabs.addTab(self.tabMatriz, "")
        self.tabFuncao = QtWidgets.QWidget()
        self.tabFuncao.setObjectName("tabFuncao")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabFuncao)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 30, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.RBFuncao1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao1.setChecked(True)
        self.RBFuncao1.setObjectName("RBFuncao1")
        self.verticalLayout_14.addWidget(self.RBFuncao1)
        self.RBFuncao2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao2.setObjectName("RBFuncao2")
        self.verticalLayout_14.addWidget(self.RBFuncao2)
        self.RBFuncao3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao3.setObjectName("RBFuncao3")
        self.verticalLayout_14.addWidget(self.RBFuncao3)
        self.RBFuncao4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao4.setObjectName("RBFuncao4")
        self.verticalLayout_14.addWidget(self.RBFuncao4)
        self.RBFuncao5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao5.setObjectName("RBFuncao5")
        self.verticalLayout_14.addWidget(self.RBFuncao5)
        self.RBFuncao6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao6.setObjectName("RBFuncao6")
        self.verticalLayout_14.addWidget(self.RBFuncao6)
        self.RBFuncao7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao7.setObjectName("RBFuncao7")
        self.verticalLayout_14.addWidget(self.RBFuncao7)
        self.RBFuncao8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao8.setObjectName("RBFuncao8")
        self.verticalLayout_14.addWidget(self.RBFuncao8)
        self.RBFuncao9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao9.setObjectName("RBFuncao9")
        self.verticalLayout_14.addWidget(self.RBFuncao9)
        self.RBFuncao10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao10.setObjectName("RBFuncao10")
        self.verticalLayout_14.addWidget(self.RBFuncao10)
        self.RBFuncao11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao11.setObjectName("RBFuncao11")
        self.verticalLayout_14.addWidget(self.RBFuncao11)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabFuncao)
        self.groupBox_8.setGeometry(QtCore.QRect(300, 40, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_8)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.XFuncao = QtWidgets.QSpinBox(self.verticalLayoutWidget_15)
        self.XFuncao.setMinimum(-99999999)
        self.XFuncao.setMaximum(999999999)
        self.XFuncao.setObjectName("XFuncao")
        self.verticalLayout_15.addWidget(self.XFuncao)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.KFuncao = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_15)
        self.KFuncao.setMinimum(-99999999.0)
        self.KFuncao.setMaximum(999999990000000.0)
        self.KFuncao.setObjectName("KFuncao")
        self.verticalLayout_15.addWidget(self.KFuncao)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tabFuncao)
        self.groupBox_9.setGeometry(QtCore.QRect(310, 270, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.ResultadoFuncao = QtWidgets.QTextBrowser(self.groupBox_9)
        self.ResultadoFuncao.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoFuncao.setObjectName("ResultadoFuncao")
        self.Tabs.addTab(self.tabFuncao, "")
        self.tabCombinatoria = QtWidgets.QWidget()
        self.tabCombinatoria.setObjectName("tabCombinatoria")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabCombinatoria)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 50, 271, 371))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 30, 251, 321))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RBPermutacaoSimples = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBPermutacaoSimples.setFont(font)
        self.RBPermutacaoSimples.setChecked(True)
        self.RBPermutacaoSimples.setObjectName("RBPermutacaoSimples")
        self.verticalLayout_12.addWidget(self.RBPermutacaoSimples)
        self.RBPermutacaoRepeticao = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBPermutacaoRepeticao.setFont(font)
        self.RBPermutacaoRepeticao.setObjectName("RBPermutacaoRepeticao")
        self.verticalLayout_12.addWidget(self.RBPermutacaoRepeticao)
        self.RBArranjoSimples = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBArranjoSimples.setFont(font)
        self.RBArranjoSimples.setObjectName("RBArranjoSimples")
        self.verticalLayout_12.addWidget(self.RBArranjoSimples)
        self.RBArranjoRepeticao = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBArranjoRepeticao.setFont(font)
        self.RBArranjoRepeticao.setObjectName("RBArranjoRepeticao")
        self.verticalLayout_12.addWidget(self.RBArranjoRepeticao)
        self.RBCombinacaoSimples = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBCombinacaoSimples.setFont(font)
        self.RBCombinacaoSimples.setObjectName("RBCombinacaoSimples")
        self.verticalLayout_12.addWidget(self.RBCombinacaoSimples)
        self.RBCombinacaoRepeticao = QtWidgets.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBCombinacaoRepeticao.setFont(font)
        self.RBCombinacaoRepeticao.setObjectName("RBCombinacaoRepeticao")
        self.verticalLayout_12.addWidget(self.RBCombinacaoRepeticao)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabCombinatoria)
        self.groupBox_5.setGeometry(QtCore.QRect(340, 60, 271, 191))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 20, 261, 151))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.NCombinatoria = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.NCombinatoria.setMaximum(99999)
        self.NCombinatoria.setObjectName("NCombinatoria")
        self.verticalLayout_13.addWidget(self.NCombinatoria)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.PCombinatoria = QtWidgets.QSpinBox(self.verticalLayoutWidget_13)
        self.PCombinatoria.setMaximum(99999)
        self.PCombinatoria.setObjectName("PCombinatoria")
        self.verticalLayout_13.addWidget(self.PCombinatoria)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabCombinatoria)
        self.groupBox_6.setGeometry(QtCore.QRect(330, 240, 361, 181))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_6)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 341, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.Tabs.addTab(self.tabCombinatoria, "")
        self.tabDerivada = QtWidgets.QWidget()
        self.tabDerivada.setObjectName("tabDerivada")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabDerivada)
        self.groupBox_10.setGeometry(QtCore.QRect(320, 260, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.ResultadoDerivada = QtWidgets.QTextBrowser(self.groupBox_10)
        self.ResultadoDerivada.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoDerivada.setObjectName("ResultadoDerivada")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabDerivada)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 20, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_11)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.RBDerivada1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada1.setChecked(True)
        self.RBDerivada1.setObjectName("RBDerivada1")
        self.verticalLayout_16.addWidget(self.RBDerivada1)
        self.RBDerivada2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada2.setObjectName("RBDerivada2")
        self.verticalLayout_16.addWidget(self.RBDerivada2)
        self.RBDerivada3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada3.setObjectName("RBDerivada3")
        self.verticalLayout_16.addWidget(self.RBDerivada3)
        self.RBDerivada4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada4.setObjectName("RBDerivada4")
        self.verticalLayout_16.addWidget(self.RBDerivada4)
        self.RBDerivada5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada5.setObjectName("RBDerivada5")
        self.verticalLayout_16.addWidget(self.RBDerivada5)
        self.RBDerivada6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada6.setObjectName("RBDerivada6")
        self.verticalLayout_16.addWidget(self.RBDerivada6)
        self.RBDerivada7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada7.setObjectName("RBDerivada7")
        self.verticalLayout_16.addWidget(self.RBDerivada7)
        self.RBDerivada8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada8.setObjectName("RBDerivada8")
        self.verticalLayout_16.addWidget(self.RBDerivada8)
        self.RBDerivada9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada9.setObjectName("RBDerivada9")
        self.verticalLayout_16.addWidget(self.RBDerivada9)
        self.RBDerivada10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada10.setObjectName("RBDerivada10")
        self.verticalLayout_16.addWidget(self.RBDerivada10)
        self.RBDerivada11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada11.setObjectName("RBDerivada11")
        self.verticalLayout_16.addWidget(self.RBDerivada11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabDerivada)
        self.groupBox_12.setGeometry(QtCore.QRect(310, 30, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_12)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.XDerivada = QtWidgets.QSpinBox(self.verticalLayoutWidget_17)
        self.XDerivada.setMinimum(-99999999)
        self.XDerivada.setMaximum(99999999)
        self.XDerivada.setObjectName("XDerivada")
        self.verticalLayout_17.addWidget(self.XDerivada)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.KDerivada = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_17)
        self.KDerivada.setMinimum(-99999999.0)
        self.KDerivada.setMaximum(99999999.99)
        self.KDerivada.setObjectName("KDerivada")
        self.verticalLayout_17.addWidget(self.KDerivada)
        self.Tabs.addTab(self.tabDerivada, "")
        self.tabIntegral = QtWidgets.QWidget()
        self.tabIntegral.setObjectName("tabIntegral")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tabIntegral)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 30, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_13)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.RBintegral1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral1.setChecked(True)
        self.RBintegral1.setObjectName("RBintegral1")
        self.verticalLayout_18.addWidget(self.RBintegral1)
        self.RBintegral2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral2.setObjectName("RBintegral2")
        self.verticalLayout_18.addWidget(self.RBintegral2)
        self.RBintegral3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral3.setObjectName("RBintegral3")
        self.verticalLayout_18.addWidget(self.RBintegral3)
        self.RBintegral4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral4.setObjectName("RBintegral4")
        self.verticalLayout_18.addWidget(self.RBintegral4)
        self.RBintegral5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral5.setObjectName("RBintegral5")
        self.verticalLayout_18.addWidget(self.RBintegral5)
        self.RBintegral6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral6.setObjectName("RBintegral6")
        self.verticalLayout_18.addWidget(self.RBintegral6)
        self.RBintegral7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral7.setObjectName("RBintegral7")
        self.verticalLayout_18.addWidget(self.RBintegral7)
        self.RBintegral8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral8.setObjectName("RBintegral8")
        self.verticalLayout_18.addWidget(self.RBintegral8)
        self.RBintegral9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral9.setObjectName("RBintegral9")
        self.verticalLayout_18.addWidget(self.RBintegral9)
        self.RBintegral10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral10.setObjectName("RBintegral10")
        self.verticalLayout_18.addWidget(self.RBintegral10)
        self.RBintegral11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral11.setObjectName("RBintegral11")
        self.verticalLayout_18.addWidget(self.RBintegral11)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tabIntegral)
        self.groupBox_14.setGeometry(QtCore.QRect(320, 270, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.ResultadoIntegral = QtWidgets.QTextBrowser(self.groupBox_14)
        self.ResultadoIntegral.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoIntegral.setObjectName("ResultadoIntegral")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tabIntegral)
        self.groupBox_15.setGeometry(QtCore.QRect(310, 40, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_15)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.XIntegral = QtWidgets.QSpinBox(self.verticalLayoutWidget_19)
        self.XIntegral.setMinimum(-99999999)
        self.XIntegral.setMaximum(99999999)
        self.XIntegral.setObjectName("XIntegral")
        self.verticalLayout_19.addWidget(self.XIntegral)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_19.addWidget(self.label_19)
        self.KIntegral = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_19)
        self.KIntegral.setObjectName("KIntegral")
        self.verticalLayout_19.addWidget(self.KIntegral)
        self.Tabs.addTab(self.tabIntegral, "")

        self.retranslateUi(Main)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Calculadora Capivara"))
        self.label.setText(_translate("Main", "Valor de k (Menor que N):"))
        self.label_2.setText(_translate("Main", "Valor de N:"))
        self.label_3.setText(_translate("Main", "Valor de A(Constante):"))
        self.label_4.setText(_translate("Main", "Valor de M:"))
        self.label_5.setText(_translate("Main", "Resultado:"))
        self.CalcularSomatoria.setText(_translate("Main", "Calcular"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabSomatoria), _translate("Main", "Somatoria"))
        self.label_6.setText(_translate("Main", "Numero de Iterações PI:"))
        self.label_8.setText(_translate("Main", "Valor aproximado de PI:"))
        self.label_7.setText(_translate("Main", "Numero de Iterações Euler(Neperiano):"))
        self.label_9.setText(_translate("Main", "Valor aproximado de Euler:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabConstante), _translate("Main", "Constante"))
        self.groupBox.setTitle(_translate("Main", "Opções"))
        self.RBnegacao.setText(_translate("Main", "¬ P"))
        self.RBconjuncao.setText(_translate("Main", " P ∧ Q"))
        self.RBdisjuncao.setText(_translate("Main", "  P ∨ Q"))
        self.RBcondicional.setText(_translate("Main", "P ∨ Q"))
        self.RBequivalencia.setText(_translate("Main", " P → Q"))
        self.RBdisjuncaoEX.setText(_translate("Main", " P ↔ Q"))
        self.groupBox_2.setTitle(_translate("Main", "Entrada:"))
        self.label_10.setText(_translate("Main", "Valor de P:"))
        self.RBTrueP.setText(_translate("Main", "TRUE"))
        self.RBFalseP.setText(_translate("Main", "FALSE"))
        self.label_11.setText(_translate("Main", "Valor de Q:"))
        self.RBTrueQ.setText(_translate("Main", "TRUE"))
        self.RBFalseQ.setText(_translate("Main", "FALSE"))
        self.groupBox_3.setTitle(_translate("Main", "Resultado:"))
        self.ResultadoLogica.setText(_translate("Main", "NULL"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabLogica), _translate("Main", "Lógica"))
        self.groupBox_16.setTitle(_translate("Main", "Opções:"))
        self.RBSomaMatriz.setText(_translate("Main", "Soma"))
        self.RBSubMatriz.setText(_translate("Main", "Subtração"))
        self.RBProdMatriz.setText(_translate("Main", "Produto"))
        self.RBDetermMatriz.setText(_translate("Main", "Determinante"))
        self.groupBox_17.setTitle(_translate("Main", "Entrada:"))
        self.label_20.setText(_translate("Main", "Tamanho da matriz:"))
        self.label_21.setText(_translate("Main", "X"))
        self.CalculaMatriz.setText(_translate("Main", "Calcular"))
        self.groupBox_18.setTitle(_translate("Main", "Resultado"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabMatriz), _translate("Main", "Matriz"))
        self.groupBox_7.setTitle(_translate("Main", "Opções:"))
        self.RBFuncao1.setText(_translate("Main", "f(x)= k"))
        self.RBFuncao2.setText(_translate("Main", "f(x)= x^k"))
        self.RBFuncao3.setText(_translate("Main", "f(x)= k^x"))
        self.RBFuncao4.setText(_translate("Main", "f(x)= logk(x)"))
        self.RBFuncao5.setText(_translate("Main", "f(x)= sen(x)"))
        self.RBFuncao6.setText(_translate("Main", "f(x)= cos(x)"))
        self.RBFuncao7.setText(_translate("Main", "f(x)= tan(x)"))
        self.RBFuncao8.setText(_translate("Main", "f(x)= √x"))
        self.RBFuncao9.setText(_translate("Main", "f(x)= 1/x"))
        self.RBFuncao10.setText(_translate("Main", "f(x)= e^x"))
        self.RBFuncao11.setText(_translate("Main", "f(x)= ln(x)"))
        self.groupBox_8.setTitle(_translate("Main", "Entrada"))
        self.label_14.setText(_translate("Main", "Valor de X:"))
        self.label_15.setText(_translate("Main", "Valor de K:"))
        self.groupBox_9.setTitle(_translate("Main", "Resultado:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabFuncao), _translate("Main", "Função"))
        self.groupBox_4.setTitle(_translate("Main", "Opções:"))
        self.RBPermutacaoSimples.setText(_translate("Main", "Permutação Simples"))
        self.RBPermutacaoRepeticao.setText(_translate("Main", "Permutação com Repetição"))
        self.RBArranjoSimples.setText(_translate("Main", "Arranjo Simples"))
        self.RBArranjoRepeticao.setText(_translate("Main", "Arranjo com Repetição"))
        self.RBCombinacaoSimples.setText(_translate("Main", "Combinação Simples"))
        self.RBCombinacaoRepeticao.setText(_translate("Main", "Combinação com Repetição"))
        self.groupBox_5.setTitle(_translate("Main", "Entrada:"))
        self.label_12.setText(_translate("Main", "Elementos no Conjunto/arranjo:"))
        self.label_13.setText(_translate("Main", "Qtd. de repetições/sub conjuntos:"))
        self.groupBox_6.setTitle(_translate("Main", "Resultado:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabCombinatoria), _translate("Main", "Combinatória"))
        self.groupBox_10.setTitle(_translate("Main", "Resultado:"))
        self.groupBox_11.setTitle(_translate("Main", "Opções a derivar:"))
        self.RBDerivada1.setText(_translate("Main", "f(x)= k"))
        self.RBDerivada2.setText(_translate("Main", "f(x)= x^k"))
        self.RBDerivada3.setText(_translate("Main", "f(x)= k^x"))
        self.RBDerivada4.setText(_translate("Main", "f(x)= logk(x)"))
        self.RBDerivada5.setText(_translate("Main", "f(x)= sen(x)"))
        self.RBDerivada6.setText(_translate("Main", "f(x)= cos(x)"))
        self.RBDerivada7.setText(_translate("Main", "f(x)= tan(x)"))
        self.RBDerivada8.setText(_translate("Main", "f(x)= √x"))
        self.RBDerivada9.setText(_translate("Main", "f(x)= 1/x"))
        self.RBDerivada10.setText(_translate("Main", "f(x)= e^x"))
        self.RBDerivada11.setText(_translate("Main", "f(x)= ln(x)"))
        self.groupBox_12.setTitle(_translate("Main", "Entrada"))
        self.label_16.setText(_translate("Main", "Valor de X:"))
        self.label_17.setText(_translate("Main", "Valor de K:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabDerivada), _translate("Main", "Derivada"))
        self.groupBox_13.setTitle(_translate("Main", "Opções a integrar:"))
        self.RBintegral1.setText(_translate("Main", "f(x)= k"))
        self.RBintegral2.setText(_translate("Main", "f(x)= x^k"))
        self.RBintegral3.setText(_translate("Main", "f(x)= k^x"))
        self.RBintegral4.setText(_translate("Main", "f(x)= logk(x)"))
        self.RBintegral5.setText(_translate("Main", "f(x)= sen(x)"))
        self.RBintegral6.setText(_translate("Main", "f(x)= cos(x)"))
        self.RBintegral7.setText(_translate("Main", "f(x)= tan(x)"))
        self.RBintegral8.setText(_translate("Main", "f(x)= √x"))
        self.RBintegral9.setText(_translate("Main", "f(x)= 1/x"))
        self.RBintegral10.setText(_translate("Main", "f(x)= e^x"))
        self.RBintegral11.setText(_translate("Main", "f(x)= ln(x)"))
        self.groupBox_14.setTitle(_translate("Main", "Resultado:"))
        self.groupBox_15.setTitle(_translate("Main", "Entrada:"))
        self.label_18.setText(_translate("Main", "Valor de X:"))
        self.label_19.setText(_translate("Main", "Valor de K:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabIntegral), _translate("Main", "Integral"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QDialog()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

