# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraCapivara.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName(_fromUtf8("Main"))
        Main.resize(956, 573)
        Main.setMinimumSize(QtCore.QSize(956, 573))
        Main.setMaximumSize(QtCore.QSize(956, 573))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Images/icone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.Tabs = QtGui.QTabWidget(Main)
        self.Tabs.setGeometry(QtCore.QRect(20, 20, 901, 521))
        self.Tabs.setObjectName(_fromUtf8("Tabs"))
        self.tabSomatoria = QtGui.QWidget()
        self.tabSomatoria.setObjectName(_fromUtf8("tabSomatoria"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 251, 331))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbSomatoria1 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria1.setText(_fromUtf8(""))
        self.rbSomatoria1.setObjectName(_fromUtf8("rbSomatoria1"))
        self.horizontalLayout.addWidget(self.rbSomatoria1)
        self.lbImgSomatoria1 = QtGui.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria1.setText(_fromUtf8(""))
        self.lbImgSomatoria1.setPixmap(QtGui.QPixmap(_fromUtf8("Images/Somatoria1.PNG")))
        self.lbImgSomatoria1.setObjectName(_fromUtf8("lbImgSomatoria1"))
        self.horizontalLayout.addWidget(self.lbImgSomatoria1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbSomatoria2 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria2.setText(_fromUtf8(""))
        self.rbSomatoria2.setObjectName(_fromUtf8("rbSomatoria2"))
        self.horizontalLayout_2.addWidget(self.rbSomatoria2)
        self.lbImgSomatoria2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria2.setText(_fromUtf8(""))
        self.lbImgSomatoria2.setPixmap(QtGui.QPixmap(_fromUtf8("Images/Somatoria2.PNG")))
        self.lbImgSomatoria2.setObjectName(_fromUtf8("lbImgSomatoria2"))
        self.horizontalLayout_2.addWidget(self.lbImgSomatoria2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rbSomatoria3 = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rbSomatoria3.setText(_fromUtf8(""))
        self.rbSomatoria3.setObjectName(_fromUtf8("rbSomatoria3"))
        self.horizontalLayout_3.addWidget(self.rbSomatoria3)
        self.lbImgSomatoria3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.lbImgSomatoria3.setText(_fromUtf8(""))
        self.lbImgSomatoria3.setPixmap(QtGui.QPixmap(_fromUtf8("Images/Somatoria3.PNG")))
        self.lbImgSomatoria3.setObjectName(_fromUtf8("lbImgSomatoria3"))
        self.horizontalLayout_3.addWidget(self.lbImgSomatoria3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 70, 195, 331))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.EntradaK = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.EntradaK.setMinimum(1)
        self.EntradaK.setMaximum(9999999)
        self.EntradaK.setObjectName(_fromUtf8("EntradaK"))
        self.verticalLayout_2.addWidget(self.EntradaK)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.EntradaN = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.EntradaN.setMaximum(9999999)
        self.EntradaN.setObjectName(_fromUtf8("EntradaN"))
        self.verticalLayout_2.addWidget(self.EntradaN)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.EntradaA = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.EntradaA.setMinimum(-99999999.0)
        self.EntradaA.setMaximum(99999999.99)
        self.EntradaA.setObjectName(_fromUtf8("EntradaA"))
        self.verticalLayout_2.addWidget(self.EntradaA)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.EntradaM = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.EntradaM.setEnabled(False)
        self.EntradaM.setMinimum(-99999999.0)
        self.EntradaM.setMaximum(99999999.99)
        self.EntradaM.setObjectName(_fromUtf8("EntradaM"))
        self.verticalLayout_2.addWidget(self.EntradaM)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabSomatoria)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(520, 110, 361, 251))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.SomatoriaResultado = QtGui.QTextBrowser(self.verticalLayoutWidget_3)
        self.SomatoriaResultado.setPlaceholderText(_fromUtf8(""))
        self.SomatoriaResultado.setObjectName(_fromUtf8("SomatoriaResultado"))
        self.verticalLayout_3.addWidget(self.SomatoriaResultado)
        self.CalcularSomatoria = QtGui.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CalcularSomatoria.setFont(font)
        self.CalcularSomatoria.setCheckable(False)
        self.CalcularSomatoria.setObjectName(_fromUtf8("CalcularSomatoria"))
        self.verticalLayout_3.addWidget(self.CalcularSomatoria)
        self.Tabs.addTab(self.tabSomatoria, _fromUtf8(""))
        self.tabConstante = QtGui.QWidget()
        self.tabConstante.setObjectName(_fromUtf8("tabConstante"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabConstante)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 50, 251, 80))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.EntradaPI = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        self.EntradaPI.setObjectName(_fromUtf8("EntradaPI"))
        self.verticalLayout_4.addWidget(self.EntradaPI)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tabConstante)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(70, 160, 258, 229))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.ResultadoPI = QtGui.QTextBrowser(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.ResultadoPI.sizePolicy().hasHeightForWidth())
        self.ResultadoPI.setSizePolicy(sizePolicy)
        self.ResultadoPI.setObjectName(_fromUtf8("ResultadoPI"))
        self.verticalLayout_5.addWidget(self.ResultadoPI)
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.tabConstante)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 50, 361, 81))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.EntradaEuler = QtGui.QSpinBox(self.verticalLayoutWidget_6)
        self.EntradaEuler.setObjectName(_fromUtf8("EntradaEuler"))
        self.verticalLayout_6.addWidget(self.EntradaEuler)
        self.verticalLayoutWidget_7 = QtGui.QWidget(self.tabConstante)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(440, 150, 281, 231))
        self.verticalLayoutWidget_7.setObjectName(_fromUtf8("verticalLayoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_7.addWidget(self.label_9)
        self.ResultadoEuler = QtGui.QTextBrowser(self.verticalLayoutWidget_7)
        self.ResultadoEuler.setObjectName(_fromUtf8("ResultadoEuler"))
        self.verticalLayout_7.addWidget(self.ResultadoEuler)
        self.Tabs.addTab(self.tabConstante, _fromUtf8(""))
        self.tabLogica = QtGui.QWidget()
        self.tabLogica.setObjectName(_fromUtf8("tabLogica"))
        self.groupBox = QtGui.QGroupBox(self.tabLogica)
        self.groupBox.setGeometry(QtCore.QRect(40, 60, 181, 351))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget_8 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 160, 321))
        self.verticalLayoutWidget_8.setObjectName(_fromUtf8("verticalLayoutWidget_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.RBnegacao = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBnegacao.setFont(font)
        self.RBnegacao.setChecked(True)
        self.RBnegacao.setObjectName(_fromUtf8("RBnegacao"))
        self.verticalLayout_8.addWidget(self.RBnegacao)
        self.RBconjuncao = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBconjuncao.setFont(font)
        self.RBconjuncao.setObjectName(_fromUtf8("RBconjuncao"))
        self.verticalLayout_8.addWidget(self.RBconjuncao)
        self.RBdisjuncao = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBdisjuncao.setFont(font)
        self.RBdisjuncao.setObjectName(_fromUtf8("RBdisjuncao"))
        self.verticalLayout_8.addWidget(self.RBdisjuncao)
        self.RBcondicional = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.RBcondicional.setFont(font)
        self.RBcondicional.setObjectName(_fromUtf8("RBcondicional"))
        self.verticalLayout_8.addWidget(self.RBcondicional)
        self.RBequivalencia = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBequivalencia.setFont(font)
        self.RBequivalencia.setObjectName(_fromUtf8("RBequivalencia"))
        self.verticalLayout_8.addWidget(self.RBequivalencia)
        self.RBdisjuncaoEX = QtGui.QRadioButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBdisjuncaoEX.setFont(font)
        self.RBdisjuncaoEX.setObjectName(_fromUtf8("RBdisjuncaoEX"))
        self.verticalLayout_8.addWidget(self.RBdisjuncaoEX)
        self.groupBox_2 = QtGui.QGroupBox(self.tabLogica)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 70, 451, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 20, 371, 111))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.RBTrueP = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBTrueP.setFont(font)
        self.RBTrueP.setChecked(True)
        self.RBTrueP.setObjectName(_fromUtf8("RBTrueP"))
        self.verticalLayout_9.addWidget(self.RBTrueP)
        self.RBFalseP = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBFalseP.setFont(font)
        self.RBFalseP.setObjectName(_fromUtf8("RBFalseP"))
        self.verticalLayout_9.addWidget(self.RBFalseP)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_10.addWidget(self.label_11)
        self.RBTrueQ = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBTrueQ.setFont(font)
        self.RBTrueQ.setObjectName(_fromUtf8("RBTrueQ"))
        self.verticalLayout_10.addWidget(self.RBTrueQ)
        self.RBFalseQ = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBFalseQ.setFont(font)
        self.RBFalseQ.setObjectName(_fromUtf8("RBFalseQ"))
        self.verticalLayout_10.addWidget(self.RBFalseQ)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.groupBox_3 = QtGui.QGroupBox(self.tabLogica)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 240, 461, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayoutWidget_11 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 10, 441, 141))
        self.verticalLayoutWidget_11.setObjectName(_fromUtf8("verticalLayoutWidget_11"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.ResultadoLogica = QtGui.QLabel(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResultadoLogica.setFont(font)
        self.ResultadoLogica.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultadoLogica.setObjectName(_fromUtf8("ResultadoLogica"))
        self.verticalLayout_11.addWidget(self.ResultadoLogica)
        self.Tabs.addTab(self.tabLogica, _fromUtf8(""))
        self.tabMatriz = QtGui.QWidget()
        self.tabMatriz.setObjectName(_fromUtf8("tabMatriz"))
        self.groupBox_16 = QtGui.QGroupBox(self.tabMatriz)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 40, 211, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.verticalLayoutWidget_20 = QtGui.QWidget(self.groupBox_16)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(10, 30, 181, 171))
        self.verticalLayoutWidget_20.setObjectName(_fromUtf8("verticalLayoutWidget_20"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_20.setMargin(0)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.RBSomaMatriz = QtGui.QRadioButton(self.verticalLayoutWidget_20)
        self.RBSomaMatriz.setObjectName(_fromUtf8("RBSomaMatriz"))
        self.verticalLayout_20.addWidget(self.RBSomaMatriz)
        self.RBSubMatriz = QtGui.QRadioButton(self.verticalLayoutWidget_20)
        self.RBSubMatriz.setObjectName(_fromUtf8("RBSubMatriz"))
        self.verticalLayout_20.addWidget(self.RBSubMatriz)
        self.RBProdMatriz = QtGui.QRadioButton(self.verticalLayoutWidget_20)
        self.RBProdMatriz.setObjectName(_fromUtf8("RBProdMatriz"))
        self.verticalLayout_20.addWidget(self.RBProdMatriz)
        self.RBDetermMatriz = QtGui.QRadioButton(self.verticalLayoutWidget_20)
        self.RBDetermMatriz.setObjectName(_fromUtf8("RBDetermMatriz"))
        self.verticalLayout_20.addWidget(self.RBDetermMatriz)
        self.groupBox_17 = QtGui.QGroupBox(self.tabMatriz)
        self.groupBox_17.setGeometry(QtCore.QRect(250, 40, 381, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_17)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_20 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_5.addWidget(self.label_20)
        self.spinBox = QtGui.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.label_21 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_5.addWidget(self.label_21)
        self.spinBox_2 = QtGui.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_5.addWidget(self.spinBox_2)
        self.CalculaMatriz = QtGui.QPushButton(self.groupBox_17)
        self.CalculaMatriz.setGeometry(QtCore.QRect(120, 140, 121, 41))
        self.CalculaMatriz.setObjectName(_fromUtf8("CalculaMatriz"))
        self.groupBox_18 = QtGui.QGroupBox(self.tabMatriz)
        self.groupBox_18.setGeometry(QtCore.QRect(30, 260, 601, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.groupBox_18)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 581, 171))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.Tabs.addTab(self.tabMatriz, _fromUtf8(""))
        self.tabFuncao = QtGui.QWidget()
        self.tabFuncao.setObjectName(_fromUtf8("tabFuncao"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabFuncao)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 30, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayoutWidget_14 = QtGui.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_14.setObjectName(_fromUtf8("verticalLayoutWidget_14"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.RBFuncao1 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao1.setChecked(True)
        self.RBFuncao1.setObjectName(_fromUtf8("RBFuncao1"))
        self.verticalLayout_14.addWidget(self.RBFuncao1)
        self.RBFuncao2 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao2.setObjectName(_fromUtf8("RBFuncao2"))
        self.verticalLayout_14.addWidget(self.RBFuncao2)
        self.RBFuncao3 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao3.setObjectName(_fromUtf8("RBFuncao3"))
        self.verticalLayout_14.addWidget(self.RBFuncao3)
        self.RBFuncao4 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao4.setObjectName(_fromUtf8("RBFuncao4"))
        self.verticalLayout_14.addWidget(self.RBFuncao4)
        self.RBFuncao5 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao5.setObjectName(_fromUtf8("RBFuncao5"))
        self.verticalLayout_14.addWidget(self.RBFuncao5)
        self.RBFuncao6 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao6.setObjectName(_fromUtf8("RBFuncao6"))
        self.verticalLayout_14.addWidget(self.RBFuncao6)
        self.RBFuncao7 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao7.setObjectName(_fromUtf8("RBFuncao7"))
        self.verticalLayout_14.addWidget(self.RBFuncao7)
        self.RBFuncao8 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao8.setObjectName(_fromUtf8("RBFuncao8"))
        self.verticalLayout_14.addWidget(self.RBFuncao8)
        self.RBFuncao9 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao9.setObjectName(_fromUtf8("RBFuncao9"))
        self.verticalLayout_14.addWidget(self.RBFuncao9)
        self.RBFuncao10 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao10.setObjectName(_fromUtf8("RBFuncao10"))
        self.verticalLayout_14.addWidget(self.RBFuncao10)
        self.RBFuncao11 = QtGui.QRadioButton(self.verticalLayoutWidget_14)
        self.RBFuncao11.setObjectName(_fromUtf8("RBFuncao11"))
        self.verticalLayout_14.addWidget(self.RBFuncao11)
        self.groupBox_8 = QtGui.QGroupBox(self.tabFuncao)
        self.groupBox_8.setGeometry(QtCore.QRect(300, 40, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayoutWidget_15 = QtGui.QWidget(self.groupBox_8)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_15.setObjectName(_fromUtf8("verticalLayoutWidget_15"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget_15)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_15.addWidget(self.label_14)
        self.XFuncao = QtGui.QSpinBox(self.verticalLayoutWidget_15)
        self.XFuncao.setMinimum(-99999999)
        self.XFuncao.setMaximum(999999999)
        self.XFuncao.setObjectName(_fromUtf8("XFuncao"))
        self.verticalLayout_15.addWidget(self.XFuncao)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget_15)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_15.addWidget(self.label_15)
        self.KFuncao = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_15)
        self.KFuncao.setMinimum(-99999999.0)
        self.KFuncao.setMaximum(9.9999999e+14)
        self.KFuncao.setObjectName(_fromUtf8("KFuncao"))
        self.verticalLayout_15.addWidget(self.KFuncao)
        self.groupBox_9 = QtGui.QGroupBox(self.tabFuncao)
        self.groupBox_9.setGeometry(QtCore.QRect(310, 270, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.ResultadoFuncao = QtGui.QTextBrowser(self.groupBox_9)
        self.ResultadoFuncao.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoFuncao.setObjectName(_fromUtf8("ResultadoFuncao"))
        self.Tabs.addTab(self.tabFuncao, _fromUtf8(""))
        self.tabCombinatoria = QtGui.QWidget()
        self.tabCombinatoria.setObjectName(_fromUtf8("tabCombinatoria"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabCombinatoria)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 50, 271, 371))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayoutWidget_12 = QtGui.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(10, 30, 251, 321))
        self.verticalLayoutWidget_12.setObjectName(_fromUtf8("verticalLayoutWidget_12"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.RBPermutacaoSimples = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBPermutacaoSimples.setFont(font)
        self.RBPermutacaoSimples.setChecked(True)
        self.RBPermutacaoSimples.setObjectName(_fromUtf8("RBPermutacaoSimples"))
        self.verticalLayout_12.addWidget(self.RBPermutacaoSimples)
        self.RBPermutacaoRepeticao = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBPermutacaoRepeticao.setFont(font)
        self.RBPermutacaoRepeticao.setObjectName(_fromUtf8("RBPermutacaoRepeticao"))
        self.verticalLayout_12.addWidget(self.RBPermutacaoRepeticao)
        self.RBArranjoSimples = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBArranjoSimples.setFont(font)
        self.RBArranjoSimples.setObjectName(_fromUtf8("RBArranjoSimples"))
        self.verticalLayout_12.addWidget(self.RBArranjoSimples)
        self.RBArranjoRepeticao = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBArranjoRepeticao.setFont(font)
        self.RBArranjoRepeticao.setObjectName(_fromUtf8("RBArranjoRepeticao"))
        self.verticalLayout_12.addWidget(self.RBArranjoRepeticao)
        self.RBCombinacaoSimples = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBCombinacaoSimples.setFont(font)
        self.RBCombinacaoSimples.setObjectName(_fromUtf8("RBCombinacaoSimples"))
        self.verticalLayout_12.addWidget(self.RBCombinacaoSimples)
        self.RBCombinacaoRepeticao = QtGui.QRadioButton(self.verticalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RBCombinacaoRepeticao.setFont(font)
        self.RBCombinacaoRepeticao.setObjectName(_fromUtf8("RBCombinacaoRepeticao"))
        self.verticalLayout_12.addWidget(self.RBCombinacaoRepeticao)
        self.groupBox_5 = QtGui.QGroupBox(self.tabCombinatoria)
        self.groupBox_5.setGeometry(QtCore.QRect(340, 60, 271, 191))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayoutWidget_13 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 20, 261, 151))
        self.verticalLayoutWidget_13.setObjectName(_fromUtf8("verticalLayoutWidget_13"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_13.addWidget(self.label_12)
        self.NCombinatoria = QtGui.QSpinBox(self.verticalLayoutWidget_13)
        self.NCombinatoria.setMaximum(99999)
        self.NCombinatoria.setObjectName(_fromUtf8("NCombinatoria"))
        self.verticalLayout_13.addWidget(self.NCombinatoria)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_13.addWidget(self.label_13)
        self.PCombinatoria = QtGui.QSpinBox(self.verticalLayoutWidget_13)
        self.PCombinatoria.setMaximum(99999)
        self.PCombinatoria.setObjectName(_fromUtf8("PCombinatoria"))
        self.verticalLayout_13.addWidget(self.PCombinatoria)
        self.groupBox_6 = QtGui.QGroupBox(self.tabCombinatoria)
        self.groupBox_6.setGeometry(QtCore.QRect(330, 240, 361, 181))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.textBrowser = QtGui.QTextBrowser(self.groupBox_6)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 341, 141))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.Tabs.addTab(self.tabCombinatoria, _fromUtf8(""))
        self.tabDerivada = QtGui.QWidget()
        self.tabDerivada.setObjectName(_fromUtf8("tabDerivada"))
        self.groupBox_10 = QtGui.QGroupBox(self.tabDerivada)
        self.groupBox_10.setGeometry(QtCore.QRect(320, 260, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.ResultadoDerivada = QtGui.QTextBrowser(self.groupBox_10)
        self.ResultadoDerivada.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoDerivada.setObjectName(_fromUtf8("ResultadoDerivada"))
        self.groupBox_11 = QtGui.QGroupBox(self.tabDerivada)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 20, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayoutWidget_16 = QtGui.QWidget(self.groupBox_11)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_16.setObjectName(_fromUtf8("verticalLayoutWidget_16"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.RBDerivada1 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada1.setChecked(True)
        self.RBDerivada1.setObjectName(_fromUtf8("RBDerivada1"))
        self.verticalLayout_16.addWidget(self.RBDerivada1)
        self.RBDerivada2 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada2.setObjectName(_fromUtf8("RBDerivada2"))
        self.verticalLayout_16.addWidget(self.RBDerivada2)
        self.RBDerivada3 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada3.setObjectName(_fromUtf8("RBDerivada3"))
        self.verticalLayout_16.addWidget(self.RBDerivada3)
        self.RBDerivada4 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada4.setObjectName(_fromUtf8("RBDerivada4"))
        self.verticalLayout_16.addWidget(self.RBDerivada4)
        self.RBDerivada5 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada5.setObjectName(_fromUtf8("RBDerivada5"))
        self.verticalLayout_16.addWidget(self.RBDerivada5)
        self.RBDerivada6 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada6.setObjectName(_fromUtf8("RBDerivada6"))
        self.verticalLayout_16.addWidget(self.RBDerivada6)
        self.RBDerivada7 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada7.setObjectName(_fromUtf8("RBDerivada7"))
        self.verticalLayout_16.addWidget(self.RBDerivada7)
        self.RBDerivada8 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada8.setObjectName(_fromUtf8("RBDerivada8"))
        self.verticalLayout_16.addWidget(self.RBDerivada8)
        self.RBDerivada9 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada9.setObjectName(_fromUtf8("RBDerivada9"))
        self.verticalLayout_16.addWidget(self.RBDerivada9)
        self.RBDerivada10 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada10.setObjectName(_fromUtf8("RBDerivada10"))
        self.verticalLayout_16.addWidget(self.RBDerivada10)
        self.RBDerivada11 = QtGui.QRadioButton(self.verticalLayoutWidget_16)
        self.RBDerivada11.setObjectName(_fromUtf8("RBDerivada11"))
        self.verticalLayout_16.addWidget(self.RBDerivada11)
        self.groupBox_12 = QtGui.QGroupBox(self.tabDerivada)
        self.groupBox_12.setGeometry(QtCore.QRect(310, 30, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayoutWidget_17 = QtGui.QWidget(self.groupBox_12)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_17.setObjectName(_fromUtf8("verticalLayoutWidget_17"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget_17)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_17.addWidget(self.label_16)
        self.XDerivada = QtGui.QSpinBox(self.verticalLayoutWidget_17)
        self.XDerivada.setMinimum(-99999999)
        self.XDerivada.setMaximum(99999999)
        self.XDerivada.setObjectName(_fromUtf8("XDerivada"))
        self.verticalLayout_17.addWidget(self.XDerivada)
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget_17)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_17.addWidget(self.label_17)
        self.KDerivada = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_17)
        self.KDerivada.setMinimum(-99999999.0)
        self.KDerivada.setMaximum(99999999.99)
        self.KDerivada.setObjectName(_fromUtf8("KDerivada"))
        self.verticalLayout_17.addWidget(self.KDerivada)
        self.Tabs.addTab(self.tabDerivada, _fromUtf8(""))
        self.tabIntegral = QtGui.QWidget()
        self.tabIntegral.setObjectName(_fromUtf8("tabIntegral"))
        self.groupBox_13 = QtGui.QGroupBox(self.tabIntegral)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 30, 271, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayoutWidget_18 = QtGui.QWidget(self.groupBox_13)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 30, 241, 424))
        self.verticalLayoutWidget_18.setObjectName(_fromUtf8("verticalLayoutWidget_18"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.RBintegral1 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral1.setChecked(True)
        self.RBintegral1.setObjectName(_fromUtf8("RBintegral1"))
        self.verticalLayout_18.addWidget(self.RBintegral1)
        self.RBintegral2 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral2.setObjectName(_fromUtf8("RBintegral2"))
        self.verticalLayout_18.addWidget(self.RBintegral2)
        self.RBintegral3 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral3.setObjectName(_fromUtf8("RBintegral3"))
        self.verticalLayout_18.addWidget(self.RBintegral3)
        self.RBintegral4 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral4.setObjectName(_fromUtf8("RBintegral4"))
        self.verticalLayout_18.addWidget(self.RBintegral4)
        self.RBintegral5 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral5.setObjectName(_fromUtf8("RBintegral5"))
        self.verticalLayout_18.addWidget(self.RBintegral5)
        self.RBintegral6 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral6.setObjectName(_fromUtf8("RBintegral6"))
        self.verticalLayout_18.addWidget(self.RBintegral6)
        self.RBintegral7 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral7.setObjectName(_fromUtf8("RBintegral7"))
        self.verticalLayout_18.addWidget(self.RBintegral7)
        self.RBintegral8 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral8.setObjectName(_fromUtf8("RBintegral8"))
        self.verticalLayout_18.addWidget(self.RBintegral8)
        self.RBintegral9 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral9.setObjectName(_fromUtf8("RBintegral9"))
        self.verticalLayout_18.addWidget(self.RBintegral9)
        self.RBintegral10 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral10.setObjectName(_fromUtf8("RBintegral10"))
        self.verticalLayout_18.addWidget(self.RBintegral10)
        self.RBintegral11 = QtGui.QRadioButton(self.verticalLayoutWidget_18)
        self.RBintegral11.setObjectName(_fromUtf8("RBintegral11"))
        self.verticalLayout_18.addWidget(self.RBintegral11)
        self.groupBox_14 = QtGui.QGroupBox(self.tabIntegral)
        self.groupBox_14.setGeometry(QtCore.QRect(320, 270, 471, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.ResultadoIntegral = QtGui.QTextBrowser(self.groupBox_14)
        self.ResultadoIntegral.setGeometry(QtCore.QRect(10, 30, 441, 161))
        self.ResultadoIntegral.setObjectName(_fromUtf8("ResultadoIntegral"))
        self.groupBox_15 = QtGui.QGroupBox(self.tabIntegral)
        self.groupBox_15.setGeometry(QtCore.QRect(310, 40, 321, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayoutWidget_19 = QtGui.QWidget(self.groupBox_15)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(10, 40, 291, 151))
        self.verticalLayoutWidget_19.setObjectName(_fromUtf8("verticalLayoutWidget_19"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget_19)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_19.addWidget(self.label_18)
        self.XIntegral = QtGui.QSpinBox(self.verticalLayoutWidget_19)
        self.XIntegral.setMinimum(-99999999)
        self.XIntegral.setMaximum(99999999)
        self.XIntegral.setObjectName(_fromUtf8("XIntegral"))
        self.verticalLayout_19.addWidget(self.XIntegral)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_19)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.KIntegral = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_19)
        self.KIntegral.setObjectName(_fromUtf8("KIntegral"))
        self.verticalLayout_19.addWidget(self.KIntegral)
        self.Tabs.addTab(self.tabIntegral, _fromUtf8(""))

        self.retranslateUi(Main)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        Main.setWindowTitle(_translate("Main", "Calculadora Capivara", None))
        self.label.setText(_translate("Main", "Valor de k (Menor que N):", None))
        self.label_2.setText(_translate("Main", "Valor de N:", None))
        self.label_3.setText(_translate("Main", "Valor de A(Constante):", None))
        self.label_4.setText(_translate("Main", "Valor de M:", None))
        self.label_5.setText(_translate("Main", "Resultado:", None))
        self.CalcularSomatoria.setText(_translate("Main", "Calcular", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabSomatoria), _translate("Main", "Somatoria", None))
        self.label_6.setText(_translate("Main", "Numero de Iterações PI:", None))
        self.label_8.setText(_translate("Main", "Valor aproximado de PI:", None))
        self.label_7.setText(_translate("Main", "Numero de Iterações Euler(Neperiano):", None))
        self.label_9.setText(_translate("Main", "Valor aproximado de Euler:", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabConstante), _translate("Main", "Constante", None))
        self.groupBox.setTitle(_translate("Main", "Opções", None))
        self.RBnegacao.setText(_translate("Main", "¬ P", None))
        self.RBconjuncao.setText(_translate("Main", " P ∧ Q", None))
        self.RBdisjuncao.setText(_translate("Main", "  P ∨ Q", None))
        self.RBcondicional.setText(_translate("Main", "P ∨ Q", None))
        self.RBequivalencia.setText(_translate("Main", " P → Q", None))
        self.RBdisjuncaoEX.setText(_translate("Main", " P ↔ Q", None))
        self.groupBox_2.setTitle(_translate("Main", "Entrada:", None))
        self.label_10.setText(_translate("Main", "Valor de P:", None))
        self.RBTrueP.setText(_translate("Main", "TRUE", None))
        self.RBFalseP.setText(_translate("Main", "FALSE", None))
        self.label_11.setText(_translate("Main", "Valor de Q:", None))
        self.RBTrueQ.setText(_translate("Main", "TRUE", None))
        self.RBFalseQ.setText(_translate("Main", "FALSE", None))
        self.groupBox_3.setTitle(_translate("Main", "Resultado:", None))
        self.ResultadoLogica.setText(_translate("Main", "NULL", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabLogica), _translate("Main", "Lógica", None))
        self.groupBox_16.setTitle(_translate("Main", "Opções:", None))
        self.RBSomaMatriz.setText(_translate("Main", "Soma", None))
        self.RBSubMatriz.setText(_translate("Main", "Subtração", None))
        self.RBProdMatriz.setText(_translate("Main", "Produto", None))
        self.RBDetermMatriz.setText(_translate("Main", "Determinante", None))
        self.groupBox_17.setTitle(_translate("Main", "Entrada:", None))
        self.label_20.setText(_translate("Main", "Tamanho da matriz:", None))
        self.label_21.setText(_translate("Main", "X", None))
        self.CalculaMatriz.setText(_translate("Main", "Calcular", None))
        self.groupBox_18.setTitle(_translate("Main", "Resultado", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabMatriz), _translate("Main", "Matriz", None))
        self.groupBox_7.setTitle(_translate("Main", "Opções:", None))
        self.RBFuncao1.setText(_translate("Main", "f(x)= k", None))
        self.RBFuncao2.setText(_translate("Main", "f(x)= x^k", None))
        self.RBFuncao3.setText(_translate("Main", "f(x)= k^x", None))
        self.RBFuncao4.setText(_translate("Main", "f(x)= logk(x)", None))
        self.RBFuncao5.setText(_translate("Main", "f(x)= sen(x)", None))
        self.RBFuncao6.setText(_translate("Main", "f(x)= cos(x)", None))
        self.RBFuncao7.setText(_translate("Main", "f(x)= tan(x)", None))
        self.RBFuncao8.setText(_translate("Main", "f(x)= √x", None))
        self.RBFuncao9.setText(_translate("Main", "f(x)= 1/x", None))
        self.RBFuncao10.setText(_translate("Main", "f(x)= e^x", None))
        self.RBFuncao11.setText(_translate("Main", "f(x)= ln(x)", None))
        self.groupBox_8.setTitle(_translate("Main", "Entrada", None))
        self.label_14.setText(_translate("Main", "Valor de X:", None))
        self.label_15.setText(_translate("Main", "Valor de K:", None))
        self.groupBox_9.setTitle(_translate("Main", "Resultado:", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabFuncao), _translate("Main", "Função", None))
        self.groupBox_4.setTitle(_translate("Main", "Opções:", None))
        self.RBPermutacaoSimples.setText(_translate("Main", "Permutação Simples", None))
        self.RBPermutacaoRepeticao.setText(_translate("Main", "Permutação com Repetição", None))
        self.RBArranjoSimples.setText(_translate("Main", "Arranjo Simples", None))
        self.RBArranjoRepeticao.setText(_translate("Main", "Arranjo com Repetição", None))
        self.RBCombinacaoSimples.setText(_translate("Main", "Combinação Simples", None))
        self.RBCombinacaoRepeticao.setText(_translate("Main", "Combinação com Repetição", None))
        self.groupBox_5.setTitle(_translate("Main", "Entrada:", None))
        self.label_12.setText(_translate("Main", "Elementos no Conjunto/arranjo:", None))
        self.label_13.setText(_translate("Main", "Qtd. de repetições/sub conjuntos:", None))
        self.groupBox_6.setTitle(_translate("Main", "Resultado:", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabCombinatoria), _translate("Main", "Combinatória", None))
        self.groupBox_10.setTitle(_translate("Main", "Resultado:", None))
        self.groupBox_11.setTitle(_translate("Main", "Opções a derivar:", None))
        self.RBDerivada1.setText(_translate("Main", "f(x)= k", None))
        self.RBDerivada2.setText(_translate("Main", "f(x)= x^k", None))
        self.RBDerivada3.setText(_translate("Main", "f(x)= k^x", None))
        self.RBDerivada4.setText(_translate("Main", "f(x)= logk(x)", None))
        self.RBDerivada5.setText(_translate("Main", "f(x)= sen(x)", None))
        self.RBDerivada6.setText(_translate("Main", "f(x)= cos(x)", None))
        self.RBDerivada7.setText(_translate("Main", "f(x)= tan(x)", None))
        self.RBDerivada8.setText(_translate("Main", "f(x)= √x", None))
        self.RBDerivada9.setText(_translate("Main", "f(x)= 1/x", None))
        self.RBDerivada10.setText(_translate("Main", "f(x)= e^x", None))
        self.RBDerivada11.setText(_translate("Main", "f(x)= ln(x)", None))
        self.groupBox_12.setTitle(_translate("Main", "Entrada", None))
        self.label_16.setText(_translate("Main", "Valor de X:", None))
        self.label_17.setText(_translate("Main", "Valor de K:", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabDerivada), _translate("Main", "Derivada", None))
        self.groupBox_13.setTitle(_translate("Main", "Opções a integrar:", None))
        self.RBintegral1.setText(_translate("Main", "f(x)= k", None))
        self.RBintegral2.setText(_translate("Main", "f(x)= x^k", None))
        self.RBintegral3.setText(_translate("Main", "f(x)= k^x", None))
        self.RBintegral4.setText(_translate("Main", "f(x)= logk(x)", None))
        self.RBintegral5.setText(_translate("Main", "f(x)= sen(x)", None))
        self.RBintegral6.setText(_translate("Main", "f(x)= cos(x)", None))
        self.RBintegral7.setText(_translate("Main", "f(x)= tan(x)", None))
        self.RBintegral8.setText(_translate("Main", "f(x)= √x", None))
        self.RBintegral9.setText(_translate("Main", "f(x)= 1/x", None))
        self.RBintegral10.setText(_translate("Main", "f(x)= e^x", None))
        self.RBintegral11.setText(_translate("Main", "f(x)= ln(x)", None))
        self.groupBox_14.setTitle(_translate("Main", "Resultado:", None))
        self.groupBox_15.setTitle(_translate("Main", "Entrada:", None))
        self.label_18.setText(_translate("Main", "Valor de X:", None))
        self.label_19.setText(_translate("Main", "Valor de K:", None))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabIntegral), _translate("Main", "Integral", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Main = QtGui.QDialog()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

